export enum ENV {
  REGION = 'REGION',
  ACCOUNT_ID = 'ACCOUNT_ID',
  TABLE_PRODUCTS = 'TABLE_PRODUCTS',
  TABLE_STOCKS = 'TABLE_STOCKS',
  CATALOG_ITEMS_QUEUE = 'CATALOG_ITEMS_QUEUE',
  CREATE_PRODUCT_TOPIC = 'CREATE_PRODUCT_TOPIC',
  CREATE_PRODUCT_SUBSCRIBTION = 'CREATE_PRODUCT_SUBSCRIBTION',
  BASIC_SUBSCRIBTION_EMAIL = 'BASIC_SUBSCRIBTION_EMAIL',
}
